@startuml

class User{
    -String userName
    -String passWord
    -String email
    -String dateOfBirth
    +void logIn()
    +void logOut()
}

class HomePage{
    -String searchBar
    -String[] categoryList
    -Video[] VideoList
    +void videoCollection()
    +void chooseVideo()
    +String getSearchBar()
    +String chooseCategory()
    +String selectedVideo()
}

class VideoUpload{
    +void isLoggedIn()
    +void uploadVideo(String nameOfVideo)
    +void manageVideo()
    +void manageMostLike()
    +void postOtherMedia()
}

class Video{
    -String videoName
    -double lengthOfVideo
    +String getName()
    +double getLengthOfVideo()
    +void comment(String comment)
}


class Driver{
    +void play(Video video)
    +void skip(Video video)
    +void share(Video video)
    +void subscribe(Video video)
}

class Play{
    +void play(Video video)
    +void skip(Video video)
    +void share(Video video)
    +void subscribe(Video video)
}

class Skip{
    +void play(Video video)
    +void skip(Video video)
    +void share(Video video)
    +void subscribe(Video video)
}

class Share{
    +void play(Video video)
    +void skip(Video video)
    +void share(Video video)
    +void subscribe(Video video)
}
class Subscribe{
    +void play(Video video)
    +void skip(Video video)
    +void share(Video video)
    +void subscribe(Video video)
}
Driver --o Play
Driver --o Skip
Driver --o Share
Driver --o Subscribe

Video --o Driver

VideoUpload --o Video
HomePage --o Video

User --o VideoUpload
User -- HomePage

@enduml